language: node_js

node_js:
  # Node 8+ includes npm@6 which has good "npm ci" command
  - 8

# if using Ubuntu 16 need this library
# https://github.com/cypress-io/cypress-documentation/pull/1647
addons:
  apt:
    packages:
    - libgconf-2-4

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
  # install dependencies and check that Cypress can run
  override:
    - npm ci
    - npm run cy:verify

script:
  # start server in the background
  - npm run dev &
  # run all Cypress tests and record on the dashboard
  - npm test -- --record --key 550e45d2-f4cf-49be-848a-e20cf0573c25
  # after all tests finish running we need
  # to kill all background jobs (like "npm start &")
  # this avoids flake in Travis jobs
  - kill $(jobs -p) || true